In [1]:
import pandas as pd
import numpy as np

autors = pd.DataFrame({'autor_id': [1, 2, 3], 'autor_name': ['Тургенев','Чехов','Островский']})

book = pd.DataFrame({'autor_id': [1, 1, 1, 2, 2, 3, 3], 'book_title': ['Отцы и дети', 'Рудин',
                    'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза',
                    'Таланты и поклонники'],'price':[450, 300, 350, 500, 450, 370, 290]})

autors_price = pd.merge(autors, book, on = 'autor_id', how = 'inner')
autors_price = autors_price.sort_values(by = 'price', ascending = False)
top5 = autors_price.head(5)
print('ТОП-5 самых дорогих книг:\n', top5)

ТОП-5 самых дорогих книг:
    autor_id  autor_name         book_title  price
3         2       Чехов   Толстый и тонкий    500
0         1    Тургенев        Отцы и дети    450
4         2       Чехов    Дама с собачкой    450
5         3  Островский              Гроза    370
2         1    Тургенев  Дворянское гнездо    350


In [2]:
p_max = autors_price.groupby('autor_name').agg({'price': 'max'})
p_min = autors_price.groupby('autor_name').agg({'price': 'min'})
p_mean = autors_price.groupby('autor_name').agg({'price': 'mean'})

p_max = p_max.rename(columns={'price':'max_price'})
p_min = p_min.rename(columns={'price':'min_price'})
p_mean = p_mean.rename(columns={'price':'mean_price'})
p_mean = p_mean.astype({'mean_price': int})

autors_stat = pd.merge(p_max, p_min, on = 'autor_name', how = 'inner')
autors_stat = pd.merge(autors_stat, p_mean, on = 'autor_name', how = 'inner')
print(autors_stat)

            max_price  min_price  mean_price
autor_name                                  
Островский        370        290         330
Тургенев          450        300         366
Чехов             500        450         475


In [3]:
autors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
print(autors_price)

   autor_id  autor_name            book_title  price    cover
3         2       Чехов      Толстый и тонкий    500  твердая
0         1    Тургенев           Отцы и дети    450   мягкая
4         2       Чехов       Дама с собачкой    450   мягкая
5         3  Островский                 Гроза    370  твердая
2         1    Тургенев     Дворянское гнездо    350  твердая
1         1    Тургенев                 Рудин    300   мягкая
6         3  Островский  Таланты и поклонники    290   мягкая


In [4]:
book_info = pd.pivot_table(autors_price, values='price', index=['autor_name'], columns=['cover'], aggfunc=sum)
print(book_info)

cover       мягкая  твердая
autor_name                 
Островский     290      370
Тургенев       750      350
Чехов          450      500


In [18]:
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
print(book_info == book_info2)

cover       мягкая  твердая
autor_name                 
Островский    True     True
Тургенев      True     True
Чехов         True     True


In [53]:
#  столбец — это признак, а строка — наблюдение.
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [54]:
mean_a = np.mean(a, axis=0)
print(mean_a)

[2.  8.4]


In [55]:
# Вычислите массив a_centered, отняв от значений массива а 
# средние значения соответствующих признаков, содержащиеся в массиве mean_a.
# Вычисление должно производиться в одно действие.
# Получившийся массив должен иметь размер 5x2.
a_centered = np.array([[a[0, 0]-mean_a[0], a[0, 1]-mean_a[1]],
                       [a[1, 0]-mean_a[0], a[1, 1]-mean_a[1]],
                       [a[2, 0]-mean_a[0], a[2, 1]-mean_a[1]],
                       [a[3, 0]-mean_a[0], a[3, 1]-mean_a[1]],
                       [a[4, 0]-mean_a[0], a[4, 1]-mean_a[1]]])

print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [56]:
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp. 
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.
a_centered_sp = 0
for i in range(len(a_centered)):
    a_centered_sp += a_centered[i, 0] * a_centered[i, 1]
print(a_centered_sp / 4)

2.0


In [57]:
at = a.transpose()
print(a)

c = np.cov(a)
print(c)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
[[12.5 15.  20.  17.5 15. ]
 [15.  18.  24.  21.  18. ]
 [20.  24.  32.  28.  24. ]
 [17.5 21.  28.  24.5 21. ]
 [15.  18.  24.  21.  18. ]]
